version: '3.9'

# Core sensearth Database Service
services:
  sensearth-db:
    container_name: sensearth-db
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensearth_db
    ports:
      - "5433:5432"
    volumes:
      - ./docker_data/sensearth_db:/var/lib/postgresql/data
    restart: always

# Monitoring Database Service
  watchdog-db:
    container_name: watchdog-db
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoring_db
    ports:
      - "5434:5432"
    volumes:
      - ./docker_data/watchdog_db:/var/lib/postgresql/data
    restart: always

# Monitoring API Service
  watchdog-api:
      container_name: watchdog-api
      build:
        context: ./monitoring
        dockerfile: Dockerfile
      working_dir: /app
      ports:
        - "8001:8001"
      depends_on:
        - watchdog-db
      restart: always

  pgadmin:
    container_name: pgadmin1
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - sensearth-db
    restart: always
