# Core sensearth Database Service
services:
  sensearth-db:
    container_name: sensearth-db
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sensearth_db
    ports:
      - "5433:5432"
    volumes:
      - ./docker_data/sensearth_db:/var/lib/postgresql/data
    restart: always

# Monitoring Database Service
  watchdog-db:
    container_name: watchdog-db
    image: timescale/timescaledb-ha:pg14-latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monitoring_db
    ports:
      - "5434:5432"
    volumes:
      - ./docker_data/watchdog_db:/var/lib/postgresql/data
    restart: always

# Monitoring API Service
  watchdog-api:
      container_name: watchdog-api
      build:
        context: ./monitoring
        dockerfile: Dockerfile
      working_dir: /app
      ports:
        - "8001:8001"
      depends_on:
        - watchdog-db
      restart: always


  middleware-api:
    container_name: middleware-api
    build:
      context: ./anomaly-detection
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - sensearth-db
      - watchdog-api
    environment:
      DB_HOST: sensearth-db
      DB_PORT: 5432
      DB_NAME: sensearth_db
      DB_USER: postgres
      DB_PASSWORD: postgres

      MONITORING_API_HOST: watchdog-api
      MONITORING_API_PORT: 8001
    restart: always

  scraper:
    container_name: scraper
    build: 
      context: ./web_scraper
      dockerfile: Dockerfile
    depends_on:
      - middleware-api
    environment:
      API_URL: http://middleware-api:8000
    volumes:
      - scraper_state:/app/state
    command: python scraper.py --config

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - sensearth-db
    restart: always

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data


volumes:
  scraper_state:
  minio_data:


