"""config_name

Revision ID: 49f25b9425c2
Revises: a9acd77eeabf
Create Date: 2025-09-04 08:21:10.987086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f25b9425c2'
down_revision: Union[str, Sequence[str], None] = 'a9acd77eeabf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datapoints')
    op.add_column('logs', sa.Column('config_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_logs_config_name'), 'logs', ['config_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_config_name'), table_name='logs')
    op.drop_column('logs', 'config_name')
    op.create_table('datapoints',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.FLOAT(), nullable=False),
    sa.Column('ftr_vector', sa.FLOAT(), nullable=False),
    sa.Column('is_anomaly', sa.INTEGER(), nullable=True),
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
