"""add changes to names, format, anomaly_detector, datapoint

Revision ID: 64f8319dabb2
Revises: 99996ae68ab8
Create Date: 2025-09-02 11:57:06.986376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f8319dabb2'
down_revision: Union[str, Sequence[str], None] = '99996ae68ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomalies')
    op.add_column('anomaly_detectors', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('anomaly_detectors', 'created_timedate')
    op.add_column('logs', sa.Column('detector_id', sa.Integer(), nullable=False))
    op.add_column('logs', sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('logs', sa.Column('end_at', sa.DateTime(), nullable=True))
    op.add_column('logs', sa.Column('tp', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('tn', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('fp', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('fn', sa.Integer(), nullable=True))
    op.drop_index('ix_logs_end_timedate', table_name='logs')
    op.drop_index('ix_logs_start_timedate', table_name='logs')
    op.create_index(op.f('ix_logs_end_at'), 'logs', ['end_at'], unique=False)
    op.create_index(op.f('ix_logs_fn'), 'logs', ['fn'], unique=False)
    op.create_index(op.f('ix_logs_fp'), 'logs', ['fp'], unique=False)
    op.create_index(op.f('ix_logs_tn'), 'logs', ['tn'], unique=False)
    op.create_index(op.f('ix_logs_tp'), 'logs', ['tp'], unique=False)
    op.create_foreign_key(None, 'logs', 'anomaly_detectors', ['detector_id'], ['id'])
    op.drop_column('logs', 'start_timedate')
    op.drop_column('logs', 'end_timedate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('end_timedate', sa.DATETIME(), nullable=True))
    op.add_column('logs', sa.Column('start_timedate', sa.DATETIME(), nullable=False))
    op.drop_constraint(None, 'logs', type_='foreignkey')
    op.drop_index(op.f('ix_logs_tp'), table_name='logs')
    op.drop_index(op.f('ix_logs_tn'), table_name='logs')
    op.drop_index(op.f('ix_logs_fp'), table_name='logs')
    op.drop_index(op.f('ix_logs_fn'), table_name='logs')
    op.drop_index(op.f('ix_logs_end_at'), table_name='logs')
    op.create_index('ix_logs_start_timedate', 'logs', ['start_timedate'], unique=False)
    op.create_index('ix_logs_end_timedate', 'logs', ['end_timedate'], unique=False)
    op.drop_column('logs', 'fn')
    op.drop_column('logs', 'fp')
    op.drop_column('logs', 'tn')
    op.drop_column('logs', 'tp')
    op.drop_column('logs', 'end_at')
    op.drop_column('logs', 'start_at')
    op.drop_column('logs', 'detector_id')
    op.add_column('anomaly_detectors', sa.Column('created_timedate', sa.DATETIME(), nullable=False))
    op.drop_column('anomaly_detectors', 'created_at')
    op.create_table('anomalies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.FLOAT(), nullable=False),
    sa.Column('ftr_vector', sa.FLOAT(), nullable=False),
    sa.Column('log_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
