"""add config&config_name column

Revision ID: 67d3c21fc6a2
Revises: 0da60a7672d4
Create Date: 2025-09-15 11:51:34.957754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d3c21fc6a2'
down_revision: Union[str, Sequence[str], None] = '0da60a7672d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anomaly_detectors', sa.Column('config', sa.Text(), nullable=False))
    op.add_column('anomaly_detectors', sa.Column('config_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_anomaly_detectors_config_name'), 'anomaly_detectors', ['config_name'], unique=False)
    op.drop_index('ix_logs_f1', table_name='logs')
    op.drop_index('ix_logs_fn', table_name='logs')
    op.drop_index('ix_logs_fp', table_name='logs')
    op.drop_index('ix_logs_precision', table_name='logs')
    op.drop_index('ix_logs_recall', table_name='logs')
    op.drop_index('ix_logs_tn', table_name='logs')
    op.drop_index('ix_logs_tp', table_name='logs')
    op.drop_column('logs', 'precision')
    op.drop_column('logs', 'recall')
    op.drop_column('logs', 'tp')
    op.drop_column('logs', 'tn')
    op.drop_column('logs', 'fn')
    op.drop_column('logs', 'fp')
    op.drop_column('logs', 'f1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('f1', sa.FLOAT(), nullable=True))
    op.add_column('logs', sa.Column('fp', sa.INTEGER(), nullable=True))
    op.add_column('logs', sa.Column('fn', sa.INTEGER(), nullable=True))
    op.add_column('logs', sa.Column('tn', sa.INTEGER(), nullable=True))
    op.add_column('logs', sa.Column('tp', sa.INTEGER(), nullable=True))
    op.add_column('logs', sa.Column('recall', sa.FLOAT(), nullable=True))
    op.add_column('logs', sa.Column('precision', sa.FLOAT(), nullable=True))
    op.create_index('ix_logs_tp', 'logs', ['tp'], unique=False)
    op.create_index('ix_logs_tn', 'logs', ['tn'], unique=False)
    op.create_index('ix_logs_recall', 'logs', ['recall'], unique=False)
    op.create_index('ix_logs_precision', 'logs', ['precision'], unique=False)
    op.create_index('ix_logs_fp', 'logs', ['fp'], unique=False)
    op.create_index('ix_logs_fn', 'logs', ['fn'], unique=False)
    op.create_index('ix_logs_f1', 'logs', ['f1'], unique=False)
    op.drop_index(op.f('ix_anomaly_detectors_config_name'), table_name='anomaly_detectors')
    op.drop_column('anomaly_detectors', 'config_name')
    op.drop_column('anomaly_detectors', 'config')
    # ### end Alembic commands ###
