"""Add duration, precision, recall and f1

Revision ID: 99996ae68ab8
Revises: 6509d6ac5f17
Create Date: 2025-08-26 12:09:18.885394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99996ae68ab8'
down_revision: Union[str, Sequence[str], None] = '6509d6ac5f17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('duration_seconds', sa.Integer(), nullable=True))
    op.add_column('logs', sa.Column('precision', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('recall', sa.Float(), nullable=True))
    op.add_column('logs', sa.Column('f1', sa.Float(), nullable=True))
    op.drop_index('ix_logs_duration_timedate', table_name='logs')
    op.create_index(op.f('ix_logs_duration_seconds'), 'logs', ['duration_seconds'], unique=False)
    op.create_index(op.f('ix_logs_f1'), 'logs', ['f1'], unique=False)
    op.create_index(op.f('ix_logs_id'), 'logs', ['id'], unique=False)
    op.create_index(op.f('ix_logs_precision'), 'logs', ['precision'], unique=False)
    op.create_index(op.f('ix_logs_recall'), 'logs', ['recall'], unique=False)
    op.drop_column('logs', 'duration_timedate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('duration_timedate', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_logs_recall'), table_name='logs')
    op.drop_index(op.f('ix_logs_precision'), table_name='logs')
    op.drop_index(op.f('ix_logs_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_f1'), table_name='logs')
    op.drop_index(op.f('ix_logs_duration_seconds'), table_name='logs')
    op.create_index('ix_logs_duration_timedate', 'logs', ['duration_timedate'], unique=False)
    op.drop_column('logs', 'f1')
    op.drop_column('logs', 'recall')
    op.drop_column('logs', 'precision')
    op.drop_column('logs', 'duration_seconds')
    # ### end Alembic commands ###
